name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Cache Konan
      uses: ./.github/actions/cache-konan
    - name: Cache Gradle
      uses: ./.github/actions/cache-gradle
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      shell: bash
    - name: Test Ksui HttpClient
      run: ./gradlew :ksui:cleanJvmTest :ksui:jvmTest --tests "xyz.mcxross.ksui.SuiHttpClientTest"
      shell: bash
